/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class', // or 'media'
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                'on-secondary-fixed': '#001f29',
                'error-container': '#ffdad6',
                'primary-fixed-dim': '#88d982',
                'secondary': '#0c6780',
                'error': '#ba1a1a',
                'surface-container': '#edeeef',
                'on-secondary': '#ffffff',
                'secondary-container': '#9ae1ff',
                'on-secondary-fixed-variant': '#004d62',
                'surface-dim': '#d9dadb',
                'tertiary-container': '#b14b6f',
                'surface-container-lowest': '#ffffff',
                'on-tertiary-container': '#ffedf0',
                'secondary-fixed': '#baeaff',
                'on-tertiary-fixed': '#3f001c',
                'secondary-fixed-dim': '#89d0ed',
                'surface-bright': '#f8f9fa',
                'surface-variant': '#e1e3e4',
                'on-secondary-container': '#09657f',
                'background': '#f8f9fa',
                'primary': '#0d631b',
                'tertiary': '#923357',
                'tertiary-fixed': '#ffd9e2',
                'primary-container': '#2e7d32',
                'surface-tint': '#1b6d24',
                'outline-variant': '#bfcaba',
                'on-primary': '#ffffff',
                'inverse-primary': '#88d982',
                'on-background': '#191c1d',
                'on-primary-container': '#cbffc2',
                'on-primary-fixed-variant': '#005312',
                'on-error-container': '#93000a',
                'inverse-surface': '#2e3132',
                'tertiary-fixed-dim': '#ffb1c7',
                'outline': '#707a6c',
                'on-primary-fixed': '#002204',
                'surface-container-high': '#e7e8e9',
                'on-surface-variant': '#40493d',
                'surface-container-low': '#f3f4f5',
                'on-surface': '#191c1d',
                'primary-fixed': '#a3f69c',
                'surface-container-highest': '#e1e3e4',
                'inverse-on-surface': '#f0f1f2',
                'on-tertiary': '#ffffff',
                'surface': '#f8f9fa',
                'on-error': '#ffffff',
                'on-tertiary-fixed-variant': '#7f2448'
            },
            borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
        },
    },
    plugins: [],
}